---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- LeftCol:
  - Media:
      - Jellyfin:
          icon: jellyfin.png
          href: http://192.168.1.155:8096
          description: Jellyfin Media Server
      - Swiparr:
          icon: swiparr.png
          href: http://192.168.1.155:8110
          description: match-based movie selection
  - Descarregues a ma:
      - qBittorrent:
          icon: qbittorrent.png
          href: http://192.168.1.155:8080
          description: qBittorrent Web UI
          widget:
            type: qbittorrent
            url: http://192.168.1.155:8080
            username: admin
            password: YOURPASSWORDHERE
            enableLeechProgress: true # optional, defaults to false
      - qui:
          icon: qui.png
          href: http://192.168.1.155:8105
          description: interface for qbittorrent
      - slskd:
          icon: slskd.png
          href: http://192.168.1.155:8099
          description: SoulSeek client to download music
      - metube:
          icon: metube.png
          href: http://192.168.1.155:8100
          description: download youtube music & videos

- CentralCol:
  - DescARRegues:
      - sonarr:
          icon: sonarr.png
          href: http://192.168.1.155:8101
          description: Automating download of shows
          widget:
            type: sonarr
            url: http://192.168.1.155:8101
            key: API_KEY_HERE
            enableQueue: true
      - radarr:
          icon: radarr.png
          href: http://192.168.1.155:8104
          description: Automating download of movies
          widget:
            type: radarr
            url: http://192.168.1.155:8104
            key: API_KEY_HERE
            enableQueue: true
      - lidarr:
          icon: lidarr.png
          href: http://192.168.1.155:8109
          description: Automating download of music
          widget:
            type: lidarr
            url: http://192.168.1.155:8109
            key: API_KEY_HERE
            enableQueue: true
      - bazarr:
          icon: bazarr.png
          href: http://192.168.1.155:8103
          description: Manage & download subtitles
      - lingarr:
          icon: lingarr.png
          href: http://192.168.1.155:8107
          description: automatically translate subtitles
      - prowlarr:
          icon: prowlarr.png
          href: http://192.168.1.155:8102
          description: API Support for torrent trackers 
          widget:
            type: prowlarr
            url: http://192.168.1.155:8102
            key: API_KEY_HERE

- RightCol:
  - Altres:
      - beelink grafana:
          icon: grafana.png
          href: http://192.168.1.155:3000/d/rYdddlPWk/node-exporter-full
          description: beelink grafana dashboard
      - jellystat:
          icon: jellystat.png
          href: http://192.168.1.155:8106
          description: stats about jellyfin media
      - Galdric grafana:
          icon: grafana.png
          href: http://192.168.1.156:3000/d/rYdddlPWk/node-exporter-full
          description: Galdric grafana dashboard
      - Wallabag:
          icon: wallabag.png
          href: http://192.168.1.155:8098
          description: Wallabag Read It Later
      - HomeAssistant:
          icon: home-assistant.png
          href: http://192.168.1.148:8123
          description: Open Home Assistant page.
